api_platform:
    # The title of the API.
    title: 'Berger australien API'

    # The description of the API.
    description: 'API for Berger australien application'

    # The version of the API.
    version: '0.0.1'

    mapping:
        #Path of entities
        paths: ['%kernel.project_dir%/src/Entity']
