# Project language
language: php

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.3

sudo: true

php:
  - 7.2

# Update composer
before-install:
  - composer self-update

before_script:
  # Parameters are copied
  - cp .env.travis .env
  # Database creation
  - psql -c 'create database symfony;' -U postgres
  # Postgis extension creation
  - psql -U postgres -c "create extension postgis" -d symfony
  # installation
  - composer install
  # Is database schema valid?
  - php bin/console doctrine:schema:validate --skip-sync
  - mv src/Resources/data/test/*.csv /tmp
  - sudo chown postgres:postgres /tmp/*.csv
  # Database migration to current version
  - php bin/console doctrine:migrations:migrate  --no-interaction

  # loading data for phpunit and codecept tests
  - php bin/console doctrine:fixtures:load -n --env=test --append
  # updates zxt_log_entries to set username to Dawny
  # - php bin/console doctrine:query:sql "UPDATE ext_log_entries SET username='Dawny' where username is null"
  # Directory used by codecoverage
  - mkdir -p build/logs

script:
  # Tests de versions
  - psql --version
  - psql -d symfony -c 'SELECT PostGIS_version();' -U postgres
  # Is database schema valid and sync?
  - php bin/console doctrine:schema:validate
  # Phpunit and codecoveralls
  - php bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  # These two lines test the migration scripts
  - php bin/console doctrine:migrations:migrate first --no-interaction
  - php bin/console doctrine:migrations:migrate --no-interaction

after_script:
  - travis_retry php vendor/bin/php-coveralls -v
  - export CODACY_PROJECT_TOKEN=9f007f22a81546f3822021ae8d7d1049
  - php vendor/bin/codacycoverage clover build/coverage/xml

notifications:
  email:
    - alexandre.tranchant@gmail.com
