App\Entity\Address:
  type: entity
  repositoryClass: App\Repository\Address
  schema: data
  table: te_address
  id:
    addressId:
      type: integer
      column: address_id
      generator:
        strategy: AUTO
  fields:
    region:
      type: text
      nullable: true
    postOfficeBoxNumber:
      type: text
      nullable: true
    postalCode:
      type: text
      nullable: true
    streetAddress:
      type: text
      nullable: true
    geometry:
      type: geometry
      nullable: true
      column: ad_geometry
  indexes:
    idx_address_locality:
      columns: [locality_id]
  manyToOne:
    locality:
      targetEntity: App\Entity\Locality
      joinColumns:
        locality_id:
          referencedColumnName: locality_id
