App\Entity\Color:
  type: entity
  schema: relation
  table: tr_color
  repositoryClass: App\Repository\ColorRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      nullable: false
    identifier:
      type: string
      nullable: false
    merle:
      type: boolean
      nullable: false
      options:
        default: false
    black:
      type: boolean
      nullable: false
      options:
        default: false
    red:
      type: boolean
      nullable: false
      options:
        default: false
  uniqueConstraints:
    uk_color:
      columns: [merle, black, red]
    uk_color_identifier:
      columns: [identifier]
