App\Entity\Country:
  type: entity
  schema: relation
  table: tr_country
  repositoryClass: App\Repository\CountryRepository
  id:
    identifier:
      type: string
      length: 2
      column: code
  fields:
    name:
      type: string
      length: 100
      nullable: false
    geometry:
      type: geometry
      nullable: true
      column: co_geom
  indexes:
    idx_country_code:
      columns: [code]
