App\Entity\Dog:
  type: entity
  schema: data
  table: te_dog
  repositoryClass: App\Repository\DogRepository
  id:
    dogId:
      type: integer
      column: dog_id
      generator:
        strategy: AUTO
  fields:
    birthday:
      type: date
      nullable: true
    breeder:
      type: text
      nullable: true
    deathday:
      type: date
      nullable: true
    name:
      type: string
      length: 255
      nullable: false
    pedigreeNumber:
      type: string
      length: 32
      nullable: true
    sex:
      type: boolean
      nullable: true
    sterilized:
      type: boolean
      nullable: false
      options:
        default: false
    tatoo:
      type: string
      length: 16
      nullable: true
    tail:
      type: integer
      nullable: false
      column: dog_tail
    uuid:
      type: guid
      unique: true
      nullable: false
  indexes:
    idx_dog_color:
      columns: [color_id]
    idx_dog_father:
      columns: [father_id]
    idx_dog_mother:
      columns: [mother_id]
    idx_dog_kennel:
      columns: [kennel_id]
    idx_dog_owner:
      columns: [owner_id]
  uniqueConstraints:
    uk_dog_uuid:
      columns: [uuid]
  oneToMany:
    checkup:
      targetEntity: App\Entity\Checkup
      mappedBy: dog
  manyToOne:
    kennel:
      targetEntity: App\Entity\Kennel
      inversedBy: dogs
      joinColumns:
        kennel_id:
          referencedColumnName: kennel_id
    owner:
      targetEntity: App\Entity\Person
      inversedBy: dogs
      joinColumns:
        owner_id:
          referencedColumnName: usr_id
    father:
      targetEntity: App\Entity\Dog
      joinColumns:
        father_id:
          referencedColumnName: dog_id
    mother:
      targetEntity: App\Entity\Dog
      joinColumns:
        mother_id:
          referencedColumnName: dog_id
    color:
      targetEntity: App\Entity\Color
      joinColumns:
        color_id:
          referencedColumnName: color_id
          nullable: false
  Gedmo:
    Tree:
      Fields:
