App\Entity\Kennel:
  type: entity
  repositoryClass: App\Repository\KennelRepository
  schema: data
  table: te_kennel
  id:
    kennelId:
      type: integer
      column: kennel_id
      generator:
        strategy: AUTO
  fields:
    legalName:
      type: text
      nullable: false
  indexes:
    idx_kennel_owner:
      columns: [owner_id]
  uniqueConstraints:
    uk_kennel_address:
      columns: [address_id]
  oneToOne:
    address:
      targetEntity: App\Entity\Address
      joinColumns:
        address_id:
          referencedColumnName: address_id
          unique: true
  oneToMany:
    dogs:
      targetEntity: App\Entity\Dog
      mappedBy: kennel
  manyToOne:
    owner:
      targetEntity: App\Entity\Person
      inversedBy: kennels
      joinColumns:
        owner_id:
          referencedColumnName: usr_id
