App\Entity\Locality:
  type: entity
  repositoryClass: App\Repository\LocalityRepository
  schema: relation
  table: tr_locality
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
      nullable: false
      column: name
    geometry:
      type: geometry
      nullable: true
      column: lo_geometry
  manyToOne:
    country:
      targetEntity: App\Entity\Country
      joinColumns:
        country_code:
          referencedColumnName: code
