App\Entity\Locality:
  type: entity
  repositoryClass: App\Repository\LocalityRepository
  schema: relation
  table: te_locality
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 200
      nullable: false
      column: full_name_nd
    geometry:
      type: geometry
      nullable: true
  oneToOne:
    country:
      targetEntity: App\Entity\Country
      joinColumns:
        cc_fips:
          referencedColumnName: cc_fips
          unique: true
